name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - LICENSE
  pull_request:
    paths-ignore:
      - README.md
      - LICENSE
  workflow_dispatch:

permissions:
  contents: read

env:
  DEVELOPER_DIR: /Applications/Xcode_26.6.app/Contents/Developer

jobs:
  build:
    name: Build & Test
    runs-on: macos-26
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Select Xcode 26.6
        run: sudo xcode-select -s /Applications/Xcode_26.6.app/Contents/Developer

      - name: Build
        run: swift build

  linux-build:
    name: Linux Test
    runs-on: ubuntu-22.04
    container: swift:6.3.3-jammy@sha256:0c9411e2f70154a16f3e5660299d618a3642a445b446efe2aa637a4d01a83d54
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Build
        run: swift build
